// <auto-generated />
namespace Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditMedium : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditMedium));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161552156_Edit-Medium"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
